version: '2'
services:
  mariadb:
    container_name: mariadb
    build: .
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secretadmin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secretadmin
      - INSTALL_ONTOP=1